Options:
  API Key: TEST
  Reasons to Ignore:
  - No Fundamentals
  Data Retention:
    Critical: 1 year
    Debug: 2 weeks
    Error: 1 year
    Information: 3 months
    Trace: 1 week
    Warning: 6 months
Exchange Codes:
  US:
    Exchanges:
    - NYSE
    - NASDAQ
    - AMEX
    Symbol Type:
    - Common Stock
    - ETF
Purge Data:
- Logs
- Imports
On Empty Database:
- Priority: 1
  Mode: Discover
  Scope: Full
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Mode: Economy
  Scope: Full
  Data Types:
  - Fundamentals
Any Day:
- Priority: 1
  Mode: Economy
  Scope: Bulk
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Mode: Economy
  Scope: Full
  Data Types:
  - Fundamentals
Sunday:
- Skip: true
  Mode: Economy
Monday:
- Skip: true
  Mode: Economy
Tuesday:
- Priority: 1
  Mode: Economy
  Scope: Bulk
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Mode: Economy
  Scope: Full
  Data Types:
  - Fundamentals
Wednesday:
- Priority: 1
  Mode: Economy
  Scope: Bulk
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Mode: Economy
  Scope: Full
  Data Types:
  - Fundamentals
Thursday:
- Priority: 1
  Mode: Economy
  Scope: Bulk
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Mode: Economy
  Scope: Full
  Data Types:
  - Fundamentals
Friday:
- Skip: false
  Priority: 1
  Mode: Economy
  Scope: Bulk
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Mode: Economy
  Scope: Full
  Data Types:
  - Fundamentals
Saturday:
- Priority: 1
  Mode: Economy
  Scope: Full
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Mode: Economy
  Scope: Full
  Data Types:
  - Fundamentals